name: "dynamic_box"

createVisualShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.025, 0.025, 0.025]
  rgbaColor: [0.9, 1.0, 0.3, 1.0]

createCollisionShape:
  shapeType: "GEOM_BOX"
  halfExtents: [0.025, 0.025, 0.025]

baseMass: 0.5
basePosition: [-0.55, 0.35, 0.2]

resetBaseVelocity:
  linearVelocity: [0.0, 0, 0]

changeDynamics:
  lateralFriction: 1.0
  spinningFriction: 0.0
  rollingFriction: 0.0
  restitution: 0.0
  linearDamping: 0.04
  angularDamping: 0.04
  contactStiffness: 2000.0
  contactDamping: 0.7
