name: "xarm"

loadURDF:
  fileName: "{rpbi_examples}/robots/xarm5_with_gripper.urdf"
  useFixedBase: 1
  basePosition: [-0.3, 0, 0]
  baseOrientation: [0, 0, 0, 1.0]




initial_joint_position: [0, 0, 0, 0, 0]
  # joint1: 0.0
  # joint2: 0.0
  # joint3: 0.0
  # joint4: 0.0
  # joint5: 0.0


initial_revolute_joint_positions_are_deg: false
is_visual_robot: false

setJointMotorControlArray:
  controlMode: "POSITION_CONTROL"


publish_joint_state_frequency: 100

broadcast_link_states: true
broadcast_link_states_frequency: 30

start_ik_callback: true
