name: "table2"

loadURDF:
  fileName: "{rpbi_examples}/robots/table.urdf"
  useFixedBase: 1
  basePosition: [0.7,0.5,-0.625]
  baseOrientation: [.0, 0.0, -0.7071067811865475, 0.7071067811865476]




# changeDynamics:
#   lateralFriction: 1.0
#   spinningFriction: 0.0
#   rollingFriction: 0.0
#   restitution: 0.0
#   linearDamping: 0.04
#   angularDamping: 0.04
#   contactStiffness: 2000.0
#   contactDamping: 0.7
